# Dockerfile for Ashling/riscv Linux builds
FROM centos:centos7
LABEL maintainer simon.cook@embecosm.com
RUN yum -y upgrade && yum -y groupinstall 'Development tools' && \
    yum -y install texinfo expat-static gmp-static expect && \
    yum -y install epel-release && \
    yum -y install meson

# Install newer toolchain components
RUN yum install -y centos-release-scl && yum install -y devtoolset-8

ENV PATH="/opt/rh/devtoolset-8/root/usr/bin:${PATH}" \
    LD_LIBRARY_PATH="/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib"

# QEMU
RUN yum -y install python3 glib2-static zlib-static && \
    curl -L https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip > ninja-linux.zip && \
    unzip ninja-linux.zip && \
    mv ninja /usr/bin && \
    chmod +x /usr/bin/ninja && \
    rm ninja-linux.zip

# Install new DejaGNU for more reliable test summary generation
RUN mkdir -p /tmp/dejagnu && cd /tmp/dejagnu && \
    curl -L https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.2.tar.gz > dejagnu-1.6.2.tar.gz && \
    tar xf dejagnu-1.6.2.tar.gz && cd dejagnu-1.6.2 && \
    ./configure && make && make install && \
    cd /tmp && rm -rf dejagnu
