# Dockerfile for Ashling/riscv Linux builds
FROM centos:centos7
LABEL maintainer simon.cook@embecosm.com
RUN yum -y upgrade && yum -y groupinstall 'Development tools' && \
    yum -y install texinfo texinfo-tex texlive tcl && \
    yum -y install epel-release && \
    yum -y install cmake3 meson patchelf && \
    ln -s /usr/bin/cmake3 /usr/bin/cmake

# Install newer toolchain components
RUN yum install -y centos-release-scl && yum install -y devtoolset-8

ENV PATH="/opt/rh/devtoolset-8/root/usr/bin:${PATH}" \
    LD_LIBRARY_PATH="/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib"
