# Dockerfile for Ashling/riscv Linux builds
FROM centos:centos7
LABEL maintainer simon.cook@embecosm.com
RUN yum -y upgrade && yum -y groupinstall 'Development tools' && \
    yum -y install texinfo tcl expat-static gmp-static && \
    yum -y install epel-release && \
    yum -y install cmake3 meson patchelf && \
    ln -s /usr/bin/cmake3 /usr/bin/cmake
